### ISSUE TITLE
Breaking out of a for loop generates jump null

### ISSUE THREAD

**Issue by YuriGen2423** [mlogjs/mlogjs#226] opened 2024-02-29 20:43 UTC
```ts
for (let i = 0; ; i++) {
    let condition = Math.floor(Math.rand(i+1))
    if (condition > i / 2) break
}
```
generates
```
set i:1:9 0
op add &t0 i:1:9 1
op rand &t1 &t0
op floor condition:2:8 &t1
op div &t2 i:1:9 2
jump null greaterThan condition:2:8 &t2
op add i:1:9 i:1:9 1
jump 1 always
```

**Comment by JeanJPNM** [comment] 2024-02-29 22:54
Duplicate of #167. Fixed by #168. You can use the [unreleased version] while the next stable version is not available.

**Closed by JeanJPNM** 2024-02-29 22:54 UTC
